import numpy as np

MAX_EPISODE_STEPS = 500
NUM_EPISODES_EVAL = 1000 # Number of episodes to average the returns over

# STATE SPACE PARAMETERS
N_BINS = 30
X_LIMIT = 10
THETA_LIMIT = np.deg2rad(90)
X_VEL_LIMIT = 4.8
THETA_VEL_LIMIT = np.deg2rad(400)

# COST FUNCTION PARAMETERS
GAMMA = 0.99
CART_COST_WEIGHT = 0.01 #C1
POLE_ANGLE_COST_WEIGHT = 0.01 #C2
TERMINAL_COST = 1 #C_TERMINAL

# VALUE ITERATION PARAMETERS
N_ITERATIONS = 1000
DELTA = 0.01

# Q-LEARNING PARAMETERS
ALPHA = 0.1    # Learning rate
EPSILON = 0.05 # Exploration rate
TRAIN_TIMESTEPS_M = 0.2 # Number of timesteps to train for
